### ISSUE TITLE
Error: Unknown or unexpected option: --cache-directory

### ISSUE THREAD

**Issue by Corovino** [Shadid12/live-video-tut#2]
Al momento de correr  npm run dev  se rompe la compilacion del ts-node

[nodemon] starting `ts-node --cache-directory .tscache ./server.ts`
C:\Users\Usuario\Documents\Projects\practices\live-video-tut\node_modules\arg\index.js:92
                                                throw err;
                                                ^

Error: Unknown or unexpected option: --cache-directory
    at arg (C:\Users\Usuario\Documents\Projects\practices\live-video-tut\node_modules\arg\index.js:90:19)
    at Object.<anonymous> (C:\Users\Usuario\Documents\Projects\practices\live-video-tut\node_modules\ts-node\dist\bin.js:13:14)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  code: 'ARG_UNKNOWN_OPTION'
}
[nodemon] app crashed - waiting for file changes before starting...
¿Desea terminar el trabajo por lotes (S/N)? 
^C
PS C:\Users\Usuario\Documents\Projects\practices\live-video-tut> npm i 
npm WARN live-chat@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

audited 2464 packages in 11.693s
found 135 vulnerabilities (102 low, 33 high)
  run `npm audit fix` to fix them, or `npm audit` for details
PS C:\Users\Usuario\Documents\Projects\practices\live-video-tut> npm uninstall ts-node 
npm WARN live-chat@1.0.0 No description
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

removed 8 packages and audited 2456 packages in 2.526s
found 135 vulnerabilities (102 low, 33 high)
  run `npm audit fix` to fix them, or `npm audit` for details
PS C:\Users\Usuario\Documents\Projects\practices\live-video-tut> npm i ts-node 
npm WARN live-chat@1.0.0 No description
npm WARN live-chat@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ ts-node@8.8.1
added 8 packages from 40 contributors and audited 2464 packages in 4.132s
found 135 vulnerabilities (102 low, 33 high)
  run `npm audit fix` to fix them, or `npm audit` for details
PS C:\Users\Usuario\Documents\Projects\practices\live-video-tut> npm run dev

> live-chat@1.0.0 dev C:\Users\Usuario\Documents\Projects\practices\live-video-tut
> nodemon --exec "ts-node" --cache-directory .tscache ./server.ts

[nodemon] 1.19.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `ts-node --cache-directory .tscache ./server.ts`
PS C:\Users\Usuario\Documents\Projects\practices\live-video-tut> npm install -D ts-node
npm notice save ts-node is being moved from dependencies to devDependencies
npm WARN live-chat@1.0.0 No description
npm WARN live-chat@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
y"} (current: {"os":"win32","arch":"x64"})

+ ts-node@8.8.1
updated 1 package and audited 2464 packages in 2.804s
found 135 vulnerabilities (102 low, 33 high)
  run `npm audit fix` to fix them, or `npm audit` for details
PS C:\Users\Usuario\Documents\Projects\practices\live-video-tut> npm install -D typescript
npm notice save typescript is being moved from dependencies to devDependencies
npm WARN live-chat@1.0.0 No description
npm WARN live-chat@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ typescript@3.8.3
updated 1 package and audited 2464 packages in 5.038s
found 135 vulnerabilities (102 low, 33 high)
  run `npm audit fix` to fix them, or `npm audit` for details
PS C:\Users\Usuario\Documents\Projects\practices\live-video-tut> npm run dev

> live-chat@1.0.0 dev C:\Users\Usuario\Documents\Projects\practices\live-video-tut
> nodemon --exec "ts-node" --cache-directory .tscache ./server.ts

[nodemon] 1.19.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `ts-node --cache-directory .tscache ./server.ts`
C:\Users\Usuario\Documents\Projects\practices\live-video-tut\node_modules\arg\index.js:90
                                                throw err;
                                                ^

Error: Unknown or unexpected option: --cache-directory
    at arg (C:\Users\Usuario\Documents\Projects\practices\live-video-tut\node_modules\arg\index.js:88:19)
    at main (C:\Users\Usuario\Documents\Projects\practices\live-video-tut\node_modules\ts-node\dist\bin.js:34:18)      
    at Object.<anonymous> (C:\Users\Usuario\Documents\Projects\practices\live-video-tut\node_modules\ts-node\dist\bin.js:418:5)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  code: 'ARG_UNKNOWN_OPTION'

**Comment by droidmanspace** [comment]
There is no argument called "--cache-directory". For more args that can be passed to [ts-node](https://www.npmjs.com/package/ts-node)
